// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kubectl

import (
	"context"

	"github.com/justenwalker/kevin/internal/command/kubectl"
	mock "github.com/stretchr/testify/mock"
)

// newMockcli creates a new instance of mockcli. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcli(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcli {
	mock := &mockcli{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcli is an autogenerated mock type for the cli type
type mockcli struct {
	mock.Mock
}

type mockcli_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcli) EXPECT() *mockcli_Expecter {
	return &mockcli_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type mockcli
func (_mock *mockcli) Apply(ctx context.Context, spec kubectl.ApplySpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.ApplySpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.ApplySpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, kubectl.ApplySpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcli_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type mockcli_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - spec kubectl.ApplySpec
func (_e *mockcli_Expecter) Apply(ctx any, spec any) *mockcli_Apply_Call {
	return &mockcli_Apply_Call{Call: _e.mock.On("Apply", ctx, spec)}
}

func (_c *mockcli_Apply_Call) Run(run func(ctx context.Context, spec kubectl.ApplySpec)) *mockcli_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kubectl.ApplySpec
		if args[1] != nil {
			arg1 = args[1].(kubectl.ApplySpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcli_Apply_Call) Return(s string, err error) *mockcli_Apply_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockcli_Apply_Call) RunAndReturn(run func(ctx context.Context, spec kubectl.ApplySpec) (string, error)) *mockcli_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockcli
func (_mock *mockcli) Delete(ctx context.Context, spec kubectl.DeleteSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.DeleteSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.DeleteSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, kubectl.DeleteSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcli_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockcli_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - spec kubectl.DeleteSpec
func (_e *mockcli_Expecter) Delete(ctx any, spec any) *mockcli_Delete_Call {
	return &mockcli_Delete_Call{Call: _e.mock.On("Delete", ctx, spec)}
}

func (_c *mockcli_Delete_Call) Run(run func(ctx context.Context, spec kubectl.DeleteSpec)) *mockcli_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kubectl.DeleteSpec
		if args[1] != nil {
			arg1 = args[1].(kubectl.DeleteSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcli_Delete_Call) Return(s string, err error) *mockcli_Delete_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockcli_Delete_Call) RunAndReturn(run func(ctx context.Context, spec kubectl.DeleteSpec) (string, error)) *mockcli_Delete_Call {
	_c.Call.Return(run)
	return _c
}
