// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wait

import (
	"context"

	"github.com/justenwalker/kevin/internal/command/kubectl"
	mock "github.com/stretchr/testify/mock"
)

// newMockkubectlCLI creates a new instance of mockkubectlCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockkubectlCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockkubectlCLI {
	mock := &mockkubectlCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockkubectlCLI is an autogenerated mock type for the kubectlCLI type
type mockkubectlCLI struct {
	mock.Mock
}

type mockkubectlCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *mockkubectlCLI) EXPECT() *mockkubectlCLI_Expecter {
	return &mockkubectlCLI_Expecter{mock: &_m.Mock}
}

// RolloutStatus provides a mock function for the type mockkubectlCLI
func (_mock *mockkubectlCLI) RolloutStatus(ctx context.Context, spec kubectl.RolloutStatusSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for RolloutStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.RolloutStatusSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.RolloutStatusSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, kubectl.RolloutStatusSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkubectlCLI_RolloutStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RolloutStatus'
type mockkubectlCLI_RolloutStatus_Call struct {
	*mock.Call
}

// RolloutStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - spec kubectl.RolloutStatusSpec
func (_e *mockkubectlCLI_Expecter) RolloutStatus(ctx any, spec any) *mockkubectlCLI_RolloutStatus_Call {
	return &mockkubectlCLI_RolloutStatus_Call{Call: _e.mock.On("RolloutStatus", ctx, spec)}
}

func (_c *mockkubectlCLI_RolloutStatus_Call) Run(run func(ctx context.Context, spec kubectl.RolloutStatusSpec)) *mockkubectlCLI_RolloutStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kubectl.RolloutStatusSpec
		if args[1] != nil {
			arg1 = args[1].(kubectl.RolloutStatusSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockkubectlCLI_RolloutStatus_Call) Return(s string, err error) *mockkubectlCLI_RolloutStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockkubectlCLI_RolloutStatus_Call) RunAndReturn(run func(ctx context.Context, spec kubectl.RolloutStatusSpec) (string, error)) *mockkubectlCLI_RolloutStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type mockkubectlCLI
func (_mock *mockkubectlCLI) Wait(ctx context.Context, spec kubectl.WaitSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.WaitSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, kubectl.WaitSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, kubectl.WaitSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkubectlCLI_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type mockkubectlCLI_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - spec kubectl.WaitSpec
func (_e *mockkubectlCLI_Expecter) Wait(ctx any, spec any) *mockkubectlCLI_Wait_Call {
	return &mockkubectlCLI_Wait_Call{Call: _e.mock.On("Wait", ctx, spec)}
}

func (_c *mockkubectlCLI_Wait_Call) Run(run func(ctx context.Context, spec kubectl.WaitSpec)) *mockkubectlCLI_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kubectl.WaitSpec
		if args[1] != nil {
			arg1 = args[1].(kubectl.WaitSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockkubectlCLI_Wait_Call) Return(s string, err error) *mockkubectlCLI_Wait_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockkubectlCLI_Wait_Call) RunAndReturn(run func(ctx context.Context, spec kubectl.WaitSpec) (string, error)) *mockkubectlCLI_Wait_Call {
	_c.Call.Return(run)
	return _c
}
