version: 2

project_name: kevin

builds:
  - id: kevin
    main: ./cmd/kevin
    binary: kevin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: kevin-relay
    main: ./cmd/kevin-relay
    binary: kevin-relay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - ids:
      - kevin
    formats:
      - tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

signs:
  - cmd: minisign
    signature: "${artifact}.minisig"
    args:
      - "-S"
      - "-s"
      - "{{ .Env.MINISIGN_KEY }}"
      - "-m"
      - "${artifact}"
      - "-x"
      - "${signature}"
    stdin: "{{ .Env.MINISIGN_PASSWORD }}"
    artifacts: checksum

dockers_v2:
  - ids:
      - kevin-relay
    dockerfile: build/relay.Dockerfile
    images:
      - ghcr.io/justenwalker/kevin/relay
    tags:
      - "{{ .Version }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999

release:
  github:
    owner: justenwalker
    name: kevin
  target_commitish: "{{ .FullCommit }}"
  prerelease: auto
