// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package plugin

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStep creates a new instance of MockStep. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStep(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStep {
	mock := &MockStep{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStep is an autogenerated mock type for the Step type
type MockStep struct {
	mock.Mock
}

type MockStep_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStep) EXPECT() *MockStep_Expecter {
	return &MockStep_Expecter{mock: &_m.Mock}
}

// Kind provides a mock function for the type MockStep
func (_mock *MockStep) Kind() StepKind {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 StepKind
	if returnFunc, ok := ret.Get(0).(func() StepKind); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(StepKind)
	}
	return r0
}

// MockStep_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type MockStep_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *MockStep_Expecter) Kind() *MockStep_Kind_Call {
	return &MockStep_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *MockStep_Kind_Call) Run(run func()) *MockStep_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_Kind_Call) Return(stepKind StepKind) *MockStep_Kind_Call {
	_c.Call.Return(stepKind)
	return _c
}

func (_c *MockStep_Kind_Call) RunAndReturn(run func() StepKind) *MockStep_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// Schema provides a mock function for the type MockStep
func (_mock *MockStep) Schema() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Schema")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockStep_Schema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schema'
type MockStep_Schema_Call struct {
	*mock.Call
}

// Schema is a helper method to define mock.On call
func (_e *MockStep_Expecter) Schema() *MockStep_Schema_Call {
	return &MockStep_Schema_Call{Call: _e.mock.On("Schema")}
}

func (_c *MockStep_Schema_Call) Run(run func()) *MockStep_Schema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_Schema_Call) Return(bytes []byte) *MockStep_Schema_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockStep_Schema_Call) RunAndReturn(run func() []byte) *MockStep_Schema_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MockStep
func (_mock *MockStep) Up(ctx context.Context, req *UpRequest, out Emitter) (*Result, error) {
	ret := _mock.Called(ctx, req, out)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 *Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *UpRequest, Emitter) (*Result, error)); ok {
		return returnFunc(ctx, req, out)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *UpRequest, Emitter) *Result); ok {
		r0 = returnFunc(ctx, req, out)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *UpRequest, Emitter) error); ok {
		r1 = returnFunc(ctx, req, out)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStep_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockStep_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
//   - req *UpRequest
//   - out Emitter
func (_e *MockStep_Expecter) Up(ctx any, req any, out any) *MockStep_Up_Call {
	return &MockStep_Up_Call{Call: _e.mock.On("Up", ctx, req, out)}
}

func (_c *MockStep_Up_Call) Run(run func(ctx context.Context, req *UpRequest, out Emitter)) *MockStep_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *UpRequest
		if args[1] != nil {
			arg1 = args[1].(*UpRequest)
		}
		var arg2 Emitter
		if args[2] != nil {
			arg2 = args[2].(Emitter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStep_Up_Call) Return(result *Result, err error) *MockStep_Up_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockStep_Up_Call) RunAndReturn(run func(ctx context.Context, req *UpRequest, out Emitter) (*Result, error)) *MockStep_Up_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDowner creates a new instance of MockDowner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDowner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDowner {
	mock := &MockDowner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDowner is an autogenerated mock type for the Downer type
type MockDowner struct {
	mock.Mock
}

type MockDowner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDowner) EXPECT() *MockDowner_Expecter {
	return &MockDowner_Expecter{mock: &_m.Mock}
}

// Down provides a mock function for the type MockDowner
func (_mock *MockDowner) Down(ctx context.Context, req *DownRequest, out Emitter) error {
	ret := _mock.Called(ctx, req, out)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DownRequest, Emitter) error); ok {
		r0 = returnFunc(ctx, req, out)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDowner_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type MockDowner_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - req *DownRequest
//   - out Emitter
func (_e *MockDowner_Expecter) Down(ctx any, req any, out any) *MockDowner_Down_Call {
	return &MockDowner_Down_Call{Call: _e.mock.On("Down", ctx, req, out)}
}

func (_c *MockDowner_Down_Call) Run(run func(ctx context.Context, req *DownRequest, out Emitter)) *MockDowner_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DownRequest
		if args[1] != nil {
			arg1 = args[1].(*DownRequest)
		}
		var arg2 Emitter
		if args[2] != nil {
			arg2 = args[2].(Emitter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDowner_Down_Call) Return(err error) *MockDowner_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDowner_Down_Call) RunAndReturn(run func(ctx context.Context, req *DownRequest, out Emitter) error) *MockDowner_Down_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExporter creates a new instance of MockExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExporter {
	mock := &MockExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExporter is an autogenerated mock type for the Exporter type
type MockExporter struct {
	mock.Mock
}

type MockExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExporter) EXPECT() *MockExporter_Expecter {
	return &MockExporter_Expecter{mock: &_m.Mock}
}

// Export provides a mock function for the type MockExporter
func (_mock *MockExporter) Export(ctx context.Context, req *ExportRequest) (*ExportResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 *ExportResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ExportRequest) (*ExportResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ExportRequest) *ExportResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ExportResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ExportRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExporter_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockExporter_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - ctx context.Context
//   - req *ExportRequest
func (_e *MockExporter_Expecter) Export(ctx any, req any) *MockExporter_Export_Call {
	return &MockExporter_Export_Call{Call: _e.mock.On("Export", ctx, req)}
}

func (_c *MockExporter_Export_Call) Run(run func(ctx context.Context, req *ExportRequest)) *MockExporter_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ExportRequest
		if args[1] != nil {
			arg1 = args[1].(*ExportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExporter_Export_Call) Return(exportResult *ExportResult, err error) *MockExporter_Export_Call {
	_c.Call.Return(exportResult, err)
	return _c
}

func (_c *MockExporter_Export_Call) RunAndReturn(run func(ctx context.Context, req *ExportRequest) (*ExportResult, error)) *MockExporter_Export_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockToolProvider creates a new instance of MockToolProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolProvider {
	mock := &MockToolProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolProvider is an autogenerated mock type for the ToolProvider type
type MockToolProvider struct {
	mock.Mock
}

type MockToolProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolProvider) EXPECT() *MockToolProvider_Expecter {
	return &MockToolProvider_Expecter{mock: &_m.Mock}
}

// CallTool provides a mock function for the type MockToolProvider
func (_mock *MockToolProvider) CallTool(ctx context.Context, req *ToolCallRequest) (*ToolCallResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 *ToolCallResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToolCallRequest) (*ToolCallResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToolCallRequest) *ToolCallResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ToolCallResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ToolCallRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolProvider_CallTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTool'
type MockToolProvider_CallTool_Call struct {
	*mock.Call
}

// CallTool is a helper method to define mock.On call
//   - ctx context.Context
//   - req *ToolCallRequest
func (_e *MockToolProvider_Expecter) CallTool(ctx any, req any) *MockToolProvider_CallTool_Call {
	return &MockToolProvider_CallTool_Call{Call: _e.mock.On("CallTool", ctx, req)}
}

func (_c *MockToolProvider_CallTool_Call) Run(run func(ctx context.Context, req *ToolCallRequest)) *MockToolProvider_CallTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ToolCallRequest
		if args[1] != nil {
			arg1 = args[1].(*ToolCallRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolProvider_CallTool_Call) Return(toolCallResult *ToolCallResult, err error) *MockToolProvider_CallTool_Call {
	_c.Call.Return(toolCallResult, err)
	return _c
}

func (_c *MockToolProvider_CallTool_Call) RunAndReturn(run func(ctx context.Context, req *ToolCallRequest) (*ToolCallResult, error)) *MockToolProvider_CallTool_Call {
	_c.Call.Return(run)
	return _c
}

// Tools provides a mock function for the type MockToolProvider
func (_mock *MockToolProvider) Tools() []ToolDef {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tools")
	}

	var r0 []ToolDef
	if returnFunc, ok := ret.Get(0).(func() []ToolDef); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ToolDef)
		}
	}
	return r0
}

// MockToolProvider_Tools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tools'
type MockToolProvider_Tools_Call struct {
	*mock.Call
}

// Tools is a helper method to define mock.On call
func (_e *MockToolProvider_Expecter) Tools() *MockToolProvider_Tools_Call {
	return &MockToolProvider_Tools_Call{Call: _e.mock.On("Tools")}
}

func (_c *MockToolProvider_Tools_Call) Run(run func()) *MockToolProvider_Tools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolProvider_Tools_Call) Return(toolDefs []ToolDef) *MockToolProvider_Tools_Call {
	_c.Call.Return(toolDefs)
	return _c
}

func (_c *MockToolProvider_Tools_Call) RunAndReturn(run func() []ToolDef) *MockToolProvider_Tools_Call {
	_c.Call.Return(run)
	return _c
}
