// Code generated by "stringer -type=RouteMode -linecomment"; DO NOT EDIT.

package plugin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RouteModeMITM-0]
	_ = x[RouteModePassthrough-1]
	_ = x[RouteModeRaw-2]
}

const _RouteMode_name = "mitmpassthroughraw"

var _RouteMode_index = [...]uint8{0, 4, 15, 18}

func (i RouteMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RouteMode_index)-1 {
		return "RouteMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RouteMode_name[_RouteMode_index[idx]:_RouteMode_index[idx+1]]
}
