// Code generated by "stringer -type=StepKind -linecomment"; DO NOT EDIT.

package plugin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StepKindUnspecified-0]
	_ = x[StepKindResource-1]
	_ = x[StepKindAction-2]
	_ = x[StepKindProbe-3]
}

const _StepKind_name = "resourceactionprobe"

var _StepKind_index = [...]uint8{0, 0, 8, 14, 19}

func (i StepKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StepKind_index)-1 {
		return "StepKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StepKind_name[_StepKind_index[idx]:_StepKind_index[idx+1]]
}
