// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pb/plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StepKind classifies what a step type is, for documentation and the
// console. It is descriptive metadata and does not change
// engine behavior.
type StepKind int32

const (
	// StepKindUnspecified is the zero value: no kind was reported.
	StepKind_STEP_KIND_UNSPECIFIED StepKind = 0
	// StepKindResource creates and destroys something.
	StepKind_STEP_KIND_RESOURCE StepKind = 1
	// StepKindAction mutates state that another system owns. StepKindAction
	// has no lifecycle of its own. It only applies changes.
	StepKind_STEP_KIND_ACTION StepKind = 2
	// StepKindProbe creates nothing. StepKindProbe only checks that something
	// else is ready.
	StepKind_STEP_KIND_PROBE StepKind = 3
)

// Enum value maps for StepKind.
var (
	StepKind_name = map[int32]string{
		0: "STEP_KIND_UNSPECIFIED",
		1: "STEP_KIND_RESOURCE",
		2: "STEP_KIND_ACTION",
		3: "STEP_KIND_PROBE",
	}
	StepKind_value = map[string]int32{
		"STEP_KIND_UNSPECIFIED": 0,
		"STEP_KIND_RESOURCE":    1,
		"STEP_KIND_ACTION":      2,
		"STEP_KIND_PROBE":       3,
	}
)

func (x StepKind) Enum() *StepKind {
	p := new(StepKind)
	*p = x
	return p
}

func (x StepKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_plugin_proto_enumTypes[0].Descriptor()
}

func (StepKind) Type() protoreflect.EnumType {
	return &file_pb_plugin_proto_enumTypes[0]
}

func (x StepKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepKind.Descriptor instead.
func (StepKind) EnumDescriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{0}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_pb_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name identifies the provider. Name must match the key in the CUE
	// plugins block.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version is the provider version. Version appears in diagnostics only.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// ConfigSchema declares #Config for the config block of this plugin. It is
	// empty when the plugin takes no configuration.
	ConfigSchema []byte `protobuf:"bytes,3,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	// Steps are the step types that this provider offers.
	Steps []*StepType `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	// Icon is a small PNG image that represents the provider. The console
	// shows Icon next to the step types of the provider. Icon is optional.
	// A provider that gives no Icon shows no icon. The maximum size of Icon
	// is 48x48 pixels. The console always displays Icon at one small fixed
	// size, regardless of the size of the source image.
	Icon          []byte `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_pb_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetConfigSchema() []byte {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *InfoResponse) GetSteps() []*StepType {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *InfoResponse) GetIcon() []byte {
	if x != nil {
		return x.Icon
	}
	return nil
}

// StepType is one step type that a provider offers.
type StepType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name identifies the step type inside its provider.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// CueSchema declares #Config for the with block of this step type.
	CueSchema []byte `protobuf:"bytes,2,opt,name=cue_schema,json=cueSchema,proto3" json:"cue_schema,omitempty"`
	// Export is true when this step type implements Export.
	Export bool `protobuf:"varint,3,opt,name=export,proto3" json:"export,omitempty"`
	// Down is true when this step type implements Down.
	Down bool `protobuf:"varint,4,opt,name=down,proto3" json:"down,omitempty"`
	// Kind classifies what this step type is.
	Kind StepKind `protobuf:"varint,5,opt,name=kind,proto3,enum=kevin.plugin.v1.StepKind" json:"kind,omitempty"`
	// Idempotent is true when this step type implements IdempotentStep and
	// indicates that the supervisor can call Up on it again safely.
	Idempotent bool `protobuf:"varint,6,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	// Tools are the MCP tools this step type offers. Empty means this step
	// type does not implement CallTool.
	Tools         []*ToolDefinition `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepType) Reset() {
	*x = StepType{}
	mi := &file_pb_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepType) ProtoMessage() {}

func (x *StepType) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepType.ProtoReflect.Descriptor instead.
func (*StepType) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *StepType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepType) GetCueSchema() []byte {
	if x != nil {
		return x.CueSchema
	}
	return nil
}

func (x *StepType) GetExport() bool {
	if x != nil {
		return x.Export
	}
	return false
}

func (x *StepType) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

func (x *StepType) GetKind() StepKind {
	if x != nil {
		return x.Kind
	}
	return StepKind_STEP_KIND_UNSPECIFIED
}

func (x *StepType) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *StepType) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolDefinition describes one MCP tool a step type offers, callable
// against a running step instance.
type ToolDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// InputSchema is the tool's parameters, an "object" JSON Schema
	// document. It must not declare a "step" property - the supervisor
	// injects that one itself before showing the schema to an MCP client.
	InputSchema   []byte `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_pb_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchema() []byte {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config is the config block of the plugin, in JSON form.
	Config        []byte       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Env           *Environment `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_pb_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigureRequest) GetEnv() *Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_pb_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{5}
}

// Environment is everything that the supervisor knows and a plugin can need.
// Environment is the same for every step in a session.
type Environment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project names the environment, and comes from the project directory.
	// Project is the prefix of every resource that kevin creates.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// Workspace is the absolute path to the .kevin state directory.
	Workspace string `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// Network is the shared network that all workloads join.
	Network string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	// CaPath is the host path to the kevin root CA certificate file. Empty
	// means no CA is available.
	CaPath string `protobuf:"bytes,4,opt,name=ca_path,json=caPath,proto3" json:"ca_path,omitempty"`
	// HttpProxyAddr is the host:port of the kevin HTTP(S) proxy.
	HttpProxyAddr string `protobuf:"bytes,5,opt,name=http_proxy_addr,json=httpProxyAddr,proto3" json:"http_proxy_addr,omitempty"`
	// ConsoleAddr is the host:port of the web console.
	ConsoleAddr string `protobuf:"bytes,6,opt,name=console_addr,json=consoleAddr,proto3" json:"console_addr,omitempty"`
	// ProxyEnv holds the proxy environment variables for a plugin to add to a workload.
	ProxyEnv map[string]string `protobuf:"bytes,7,rep,name=proxy_env,json=proxyEnv,proto3" json:"proxy_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Domain is the base name of the environment, such as "kevin.home".
	Domain string `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	// Relay is the address of the in-network relay. A workload uses it for DNS.
	Relay string `protobuf:"bytes,9,opt,name=relay,proto3" json:"relay,omitempty"`
	// ProjectDir is the absolute path of the directory that holds kevin.cue.
	ProjectDir string `protobuf:"bytes,10,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	// Engine names the container runtime that a plugin should use, such as
	// "docker" or "podman". Empty means "docker", the only engine kevin
	// ships today.
	Engine string `protobuf:"bytes,11,opt,name=engine,proto3" json:"engine,omitempty"`
	// EngineConfig is the marshaled bytes of the config message for Engine,
	// such as DockerEngineConfig. Engine says which message to unmarshal
	// into.
	EngineConfig []byte `protobuf:"bytes,12,opt,name=engine_config,json=engineConfig,proto3" json:"engine_config,omitempty"`
	// Scope is which DAG this step belongs to: "setup" or "env". A plugin
	// should carry it as the "kevin.scope" label alongside
	// "kevin.project"/"kevin.urn".
	Scope string `protobuf:"bytes,13,opt,name=scope,proto3" json:"scope,omitempty"`
	// RelaySocks5Addr is the host-reachable address of the relay's SOCKS5
	// gateway. A plugin builds a "socks5://<addr>/<target>" upstream against
	// it to reach a docker-network address through a single host port
	// instead of a dedicated published port.
	RelaySocks5Addr string `protobuf:"bytes,14,opt,name=relay_socks5_addr,json=relaySocks5Addr,proto3" json:"relay_socks5_addr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_pb_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Environment) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Environment) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *Environment) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Environment) GetCaPath() string {
	if x != nil {
		return x.CaPath
	}
	return ""
}

func (x *Environment) GetHttpProxyAddr() string {
	if x != nil {
		return x.HttpProxyAddr
	}
	return ""
}

func (x *Environment) GetConsoleAddr() string {
	if x != nil {
		return x.ConsoleAddr
	}
	return ""
}

func (x *Environment) GetProxyEnv() map[string]string {
	if x != nil {
		return x.ProxyEnv
	}
	return nil
}

func (x *Environment) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Environment) GetRelay() string {
	if x != nil {
		return x.Relay
	}
	return ""
}

func (x *Environment) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *Environment) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *Environment) GetEngineConfig() []byte {
	if x != nil {
		return x.EngineConfig
	}
	return nil
}

func (x *Environment) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Environment) GetRelaySocks5Addr() string {
	if x != nil {
		return x.RelaySocks5Addr
	}
	return ""
}

// DockerEngineConfig is the engine_config message for the "docker" engine.
// It carries no fields today: the docker CLI wrapper needs nothing beyond
// Network. Add fields here as real Docker-specific settings arise, such as
// a non-default socket path.
type DockerEngineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerEngineConfig) Reset() {
	*x = DockerEngineConfig{}
	mi := &file_pb_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerEngineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerEngineConfig) ProtoMessage() {}

func (x *DockerEngineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerEngineConfig.ProtoReflect.Descriptor instead.
func (*DockerEngineConfig) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{7}
}

// Value is one output value - a step's published output, an upstream
// dependency's value, or a console Detail's content.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	Kind isValue_Kind `protobuf_oneof:"kind"`
	// Sensitive marks this value as secret: it must never be logged or
	// displayed in full. It sits outside "kind" - sensitivity is a property
	// of any value, not a kind of value.
	Sensitive     bool `protobuf:"varint,10,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_pb_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

// Outputs are the values that a step publishes for its dependents.
type Outputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outputs) Reset() {
	*x = Outputs{}
	mi := &file_pb_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outputs) ProtoMessage() {}

func (x *Outputs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outputs.ProtoReflect.Descriptor instead.
func (*Outputs) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Outputs) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Step is the name of the step to run.
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// Type is the step type that this node uses.
	Type string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Env  *Environment `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	// Config is the with block of the step, in JSON form.
	Config []byte `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Deps maps the name of each upstream step to the outputs of that step.
	Deps          map[string]*Outputs `protobuf:"bytes,5,rep,name=deps,proto3" json:"deps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpRequest) Reset() {
	*x = UpRequest{}
	mi := &file_pb_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRequest) ProtoMessage() {}

func (x *UpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRequest.ProtoReflect.Descriptor instead.
func (*UpRequest) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *UpRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *UpRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpRequest) GetEnv() *Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *UpRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpRequest) GetDeps() map[string]*Outputs {
	if x != nil {
		return x.Deps
	}
	return nil
}

type DownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Step is the name of the step to destroy.
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// Type is the step type that this node uses.
	Type string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Env  *Environment `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	// Config is the with block of the step, in JSON form.
	Config []byte `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Deps maps the name of each upstream step to the outputs of that step.
	Deps map[string]*Outputs `protobuf:"bytes,5,rep,name=deps,proto3" json:"deps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Outputs is what Up published for this step.
	// Outputs are used by other steps as inputs to chain together more complex setup operations.
	// These are passed to other steps using its Config.
	Outputs       *Outputs `protobuf:"bytes,6,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownRequest) Reset() {
	*x = DownRequest{}
	mi := &file_pb_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRequest) ProtoMessage() {}

func (x *DownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRequest.ProtoReflect.Descriptor instead.
func (*DownRequest) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *DownRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *DownRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DownRequest) GetEnv() *Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DownRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DownRequest) GetDeps() map[string]*Outputs {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *DownRequest) GetOutputs() *Outputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_Log
	//	*Event_Progress
	//	*Event_Result
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pb_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*Event_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *Event) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*Event_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *Event) GetResult() *Result {
	if x != nil {
		if x, ok := x.Event.(*Event_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Log struct {
	Log *LogLine `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type Event_Progress struct {
	Progress *Progress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type Event_Result struct {
	Result *Result `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*Event_Log) isEvent_Event() {}

func (*Event_Progress) isEvent_Event() {}

func (*Event_Result) isEvent_Event() {}

type LogLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream is "stdout" or "stderr".
	Stream        string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UnixNano      int64  `protobuf:"varint,3,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_pb_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LogLine) GetUnixNano() int64 {
	if x != nil {
		return x.UnixNano
	}
	return 0
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Current       int64                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_pb_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *Progress) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Progress) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Progress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Result ends an Up stream.
type Result struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Outputs *Outputs               `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	// Routes are the hostnames that this step serves.
	Routes []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	// EgressAllow lists the external hosts that this step can reach.
	EgressAllow []string `protobuf:"bytes,3,rep,name=egress_allow,json=egressAllow,proto3" json:"egress_allow,omitempty"`
	// ExposedPorts are raw TCP or UDP endpoints that this step publishes directly to the host.
	// ExposedPorts do not go through the HTTP proxy.
	ExposedPorts []*ExposedPort `protobuf:"bytes,4,rep,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`
	// Details are the rows that this step shows on its web console card.
	Details       []*Detail `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pb_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *Result) GetOutputs() *Outputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Result) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Result) GetEgressAllow() []string {
	if x != nil {
		return x.EgressAllow
	}
	return nil
}

func (x *Result) GetExposedPorts() []*ExposedPort {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

func (x *Result) GetDetails() []*Detail {
	if x != nil {
		return x.Details
	}
	return nil
}

// ExposedPort is a raw TCP or UDP endpoint that a step publishes directly to
// the host.
type ExposedPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Protocol is "tcp" or "udp".
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Upstream is the host-reachable address, such as "127.0.0.1:54321".
	Upstream      string `protobuf:"bytes,3,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposedPort) Reset() {
	*x = ExposedPort{}
	mi := &file_pb_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposedPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposedPort) ProtoMessage() {}

func (x *ExposedPort) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposedPort.ProtoReflect.Descriptor instead.
func (*ExposedPort) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ExposedPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExposedPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ExposedPort) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

// Detail is one extra piece of information that a step shows on its
// console card. Detail is purely descriptive. Unlike Route or ExposedPort,
// Detail drives no proxy or DAG behavior.
type Detail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Copyable shows a copy-to-clipboard button next to value.
	Copyable bool `protobuf:"varint,3,opt,name=copyable,proto3" json:"copyable,omitempty"`
	// Href, when set, renders value as a link to this URL instead of plain
	// text.
	Href          string `protobuf:"bytes,4,opt,name=href,proto3" json:"href,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail) Reset() {
	*x = Detail{}
	mi := &file_pb_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *Detail) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Detail) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Detail) GetCopyable() bool {
	if x != nil {
		return x.Copyable
	}
	return false
}

func (x *Detail) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

type ExportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Step is the name of the step to export.
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// Type is the step type that this node uses.
	Type string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Env  *Environment `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	// Config is the with block of the step, in JSON form.
	Config        []byte `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_pb_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ExportRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ExportRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExportRequest) GetEnv() *Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExportRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type ExportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Out holds the step's outputs in structured form - the same Value shape
	// Outputs uses, each value optionally marked sensitive. A cross-scope
	// "needs: [\"setup.<name>\"]" reference, and a "commands:" entry's "run"
	// ("${needs.<step>.out.<key>}"), both resolve against this.
	Out           *Outputs `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_pb_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ExportResponse) GetOut() *Outputs {
	if x != nil {
		return x.Out
	}
	return nil
}

type ToolCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Step is the name of the step instance to call the tool against.
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// Type is the step type that this node uses.
	Type string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Env  *Environment `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	// Config is the with block of the step, in JSON form, CEL-rendered the
	// same way UpRequest.Config is.
	Config []byte `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Deps maps the name of each upstream step to the outputs of that step.
	Deps map[string]*Outputs `protobuf:"bytes,5,rep,name=deps,proto3" json:"deps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tool is the name from the step type's ToolDefinition.
	Tool string `protobuf:"bytes,6,opt,name=tool,proto3" json:"tool,omitempty"`
	// Arguments is the MCP call's own arguments, in JSON form, with the
	// supervisor-injected "step" property already removed.
	Arguments     []byte `protobuf:"bytes,7,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRequest) Reset() {
	*x = ToolCallRequest{}
	mi := &file_pb_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRequest) ProtoMessage() {}

func (x *ToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRequest.ProtoReflect.Descriptor instead.
func (*ToolCallRequest) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ToolCallRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ToolCallRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCallRequest) GetEnv() *Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ToolCallRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ToolCallRequest) GetDeps() map[string]*Outputs {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *ToolCallRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCallRequest) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ToolCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content is the tool's result, JSON-encoded - any JSON value (object,
	// array, or primitive), surfaced to the MCP client as structured
	// content.
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsError bool   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// ErrorMessage is shown to the MCP client when IsError is true.
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallResponse) Reset() {
	*x = ToolCallResponse{}
	mi := &file_pb_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResponse) ProtoMessage() {}

func (x *ToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallResponse.ProtoReflect.Descriptor instead.
func (*ToolCallResponse) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *ToolCallResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ToolCallResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolCallResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host is the hostname that clients use.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Upstream is the address to forward to. The address must be reachable on the docker network.
	Upstream string `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// Tls is true when the upstream itself speaks TLS.
	Tls           bool `protobuf:"varint,3,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_pb_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *Route) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Route) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *Route) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

// UserMessage carries a human-facing error message as a detail on the gRPC
// status of a failed Configure, Up, Down, or Export call. A plugin attaches
// one when its step wraps an error with a message meant for a human, so the
// supervisor can show that instead of the raw error chain.
type UserMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is the format string the message was built from, with %s verbs -
	// a stable candidate key for a future translation catalog. The
	// supervisor renders it with Args today (fmt.Sprintf(Key, Args...)); a
	// translation catalog later looks Key up and renders Args into a
	// localized template instead.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Args are the format arguments, each in its plain text form, in the
	// order Key's verbs expect them.
	Args          []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_pb_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_pb_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *UserMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserMessage) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_pb_plugin_proto protoreflect.FileDescriptor

const file_pb_plugin_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/plugin.proto\x12\x0fkevin.plugin.v1\"\r\n" +
	"\vInfoRequest\"\xa6\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\rconfig_schema\x18\x03 \x01(\fR\fconfigSchema\x12/\n" +
	"\x05steps\x18\x04 \x03(\v2\x19.kevin.plugin.v1.StepTypeR\x05steps\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\fR\x04icon\"\xef\x01\n" +
	"\bStepType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cue_schema\x18\x02 \x01(\fR\tcueSchema\x12\x16\n" +
	"\x06export\x18\x03 \x01(\bR\x06export\x12\x12\n" +
	"\x04down\x18\x04 \x01(\bR\x04down\x12-\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x19.kevin.plugin.v1.StepKindR\x04kind\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x06 \x01(\bR\n" +
	"idempotent\x125\n" +
	"\x05tools\x18\a \x03(\v2\x1f.kevin.plugin.v1.ToolDefinitionR\x05tools\"i\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\fR\vinputSchema\"Z\n" +
	"\x10ConfigureRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12.\n" +
	"\x03env\x18\x02 \x01(\v2\x1c.kevin.plugin.v1.EnvironmentR\x03env\"\x13\n" +
	"\x11ConfigureResponse\"\x97\x04\n" +
	"\vEnvironment\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x17\n" +
	"\aca_path\x18\x04 \x01(\tR\x06caPath\x12&\n" +
	"\x0fhttp_proxy_addr\x18\x05 \x01(\tR\rhttpProxyAddr\x12!\n" +
	"\fconsole_addr\x18\x06 \x01(\tR\vconsoleAddr\x12G\n" +
	"\tproxy_env\x18\a \x03(\v2*.kevin.plugin.v1.Environment.ProxyEnvEntryR\bproxyEnv\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12\x14\n" +
	"\x05relay\x18\t \x01(\tR\x05relay\x12\x1f\n" +
	"\vproject_dir\x18\n" +
	" \x01(\tR\n" +
	"projectDir\x12\x16\n" +
	"\x06engine\x18\v \x01(\tR\x06engine\x12#\n" +
	"\rengine_config\x18\f \x01(\fR\fengineConfig\x12\x14\n" +
	"\x05scope\x18\r \x01(\tR\x05scope\x12*\n" +
	"\x11relay_socks5_addr\x18\x0e \x01(\tR\x0frelaySocks5Addr\x1a;\n" +
	"\rProxyEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12DockerEngineConfig\"R\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1c\n" +
	"\tsensitive\x18\n" +
	" \x01(\bR\tsensitiveB\x06\n" +
	"\x04kind\"\x9a\x01\n" +
	"\aOutputs\x12<\n" +
	"\x06values\x18\x01 \x03(\v2$.kevin.plugin.v1.Outputs.ValuesEntryR\x06values\x1aQ\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.kevin.plugin.v1.ValueR\x05value:\x028\x01\"\x88\x02\n" +
	"\tUpRequest\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12.\n" +
	"\x03env\x18\x03 \x01(\v2\x1c.kevin.plugin.v1.EnvironmentR\x03env\x12\x16\n" +
	"\x06config\x18\x04 \x01(\fR\x06config\x128\n" +
	"\x04deps\x18\x05 \x03(\v2$.kevin.plugin.v1.UpRequest.DepsEntryR\x04deps\x1aQ\n" +
	"\tDepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.kevin.plugin.v1.OutputsR\x05value:\x028\x01\"\xc0\x02\n" +
	"\vDownRequest\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12.\n" +
	"\x03env\x18\x03 \x01(\v2\x1c.kevin.plugin.v1.EnvironmentR\x03env\x12\x16\n" +
	"\x06config\x18\x04 \x01(\fR\x06config\x12:\n" +
	"\x04deps\x18\x05 \x03(\v2&.kevin.plugin.v1.DownRequest.DepsEntryR\x04deps\x122\n" +
	"\aoutputs\x18\x06 \x01(\v2\x18.kevin.plugin.v1.OutputsR\aoutputs\x1aQ\n" +
	"\tDepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.kevin.plugin.v1.OutputsR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x05Event\x12,\n" +
	"\x03log\x18\x01 \x01(\v2\x18.kevin.plugin.v1.LogLineH\x00R\x03log\x127\n" +
	"\bprogress\x18\x02 \x01(\v2\x19.kevin.plugin.v1.ProgressH\x00R\bprogress\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x17.kevin.plugin.v1.ResultH\x00R\x06resultB\a\n" +
	"\x05event\"R\n" +
	"\aLogLine\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\tunix_nano\x18\x03 \x01(\x03R\bunixNano\"P\n" +
	"\bProgress\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x03R\acurrent\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\x85\x02\n" +
	"\x06Result\x122\n" +
	"\aoutputs\x18\x01 \x01(\v2\x18.kevin.plugin.v1.OutputsR\aoutputs\x12.\n" +
	"\x06routes\x18\x02 \x03(\v2\x16.kevin.plugin.v1.RouteR\x06routes\x12!\n" +
	"\fegress_allow\x18\x03 \x03(\tR\vegressAllow\x12A\n" +
	"\rexposed_ports\x18\x04 \x03(\v2\x1c.kevin.plugin.v1.ExposedPortR\fexposedPorts\x121\n" +
	"\adetails\x18\x05 \x03(\v2\x17.kevin.plugin.v1.DetailR\adetails\"Y\n" +
	"\vExposedPort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1a\n" +
	"\bupstream\x18\x03 \x01(\tR\bupstream\"|\n" +
	"\x06Detail\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.kevin.plugin.v1.ValueR\x05value\x12\x1a\n" +
	"\bcopyable\x18\x03 \x01(\bR\bcopyable\x12\x12\n" +
	"\x04href\x18\x04 \x01(\tR\x04href\"\x7f\n" +
	"\rExportRequest\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12.\n" +
	"\x03env\x18\x03 \x01(\v2\x1c.kevin.plugin.v1.EnvironmentR\x03env\x12\x16\n" +
	"\x06config\x18\x04 \x01(\fR\x06config\"<\n" +
	"\x0eExportResponse\x12*\n" +
	"\x03out\x18\x02 \x01(\v2\x18.kevin.plugin.v1.OutputsR\x03out\"\xc6\x02\n" +
	"\x0fToolCallRequest\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12.\n" +
	"\x03env\x18\x03 \x01(\v2\x1c.kevin.plugin.v1.EnvironmentR\x03env\x12\x16\n" +
	"\x06config\x18\x04 \x01(\fR\x06config\x12>\n" +
	"\x04deps\x18\x05 \x03(\v2*.kevin.plugin.v1.ToolCallRequest.DepsEntryR\x04deps\x12\x12\n" +
	"\x04tool\x18\x06 \x01(\tR\x04tool\x12\x1c\n" +
	"\targuments\x18\a \x01(\fR\targuments\x1aQ\n" +
	"\tDepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.kevin.plugin.v1.OutputsR\x05value:\x028\x01\"l\n" +
	"\x10ToolCallResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"I\n" +
	"\x05Route\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\tR\bupstream\x12\x10\n" +
	"\x03tls\x18\x03 \x01(\bR\x03tls\"3\n" +
	"\vUserMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args*h\n" +
	"\bStepKind\x12\x19\n" +
	"\x15STEP_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STEP_KIND_RESOURCE\x10\x01\x12\x14\n" +
	"\x10STEP_KIND_ACTION\x10\x02\x12\x13\n" +
	"\x0fSTEP_KIND_PROBE\x10\x032\xb9\x03\n" +
	"\x06Plugin\x12C\n" +
	"\x04Info\x12\x1c.kevin.plugin.v1.InfoRequest\x1a\x1d.kevin.plugin.v1.InfoResponse\x12R\n" +
	"\tConfigure\x12!.kevin.plugin.v1.ConfigureRequest\x1a\".kevin.plugin.v1.ConfigureResponse\x12:\n" +
	"\x02Up\x12\x1a.kevin.plugin.v1.UpRequest\x1a\x16.kevin.plugin.v1.Event0\x01\x12>\n" +
	"\x04Down\x12\x1c.kevin.plugin.v1.DownRequest\x1a\x16.kevin.plugin.v1.Event0\x01\x12I\n" +
	"\x06Export\x12\x1e.kevin.plugin.v1.ExportRequest\x1a\x1f.kevin.plugin.v1.ExportResponse\x12O\n" +
	"\bCallTool\x12 .kevin.plugin.v1.ToolCallRequest\x1a!.kevin.plugin.v1.ToolCallResponseB,Z*github.com/justenwalker/kevin/protos/pb;pbb\x06proto3"

var (
	file_pb_plugin_proto_rawDescOnce sync.Once
	file_pb_plugin_proto_rawDescData []byte
)

func file_pb_plugin_proto_rawDescGZIP() []byte {
	file_pb_plugin_proto_rawDescOnce.Do(func() {
		file_pb_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_plugin_proto_rawDesc), len(file_pb_plugin_proto_rawDesc)))
	})
	return file_pb_plugin_proto_rawDescData
}

var file_pb_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pb_plugin_proto_goTypes = []any{
	(StepKind)(0),              // 0: kevin.plugin.v1.StepKind
	(*InfoRequest)(nil),        // 1: kevin.plugin.v1.InfoRequest
	(*InfoResponse)(nil),       // 2: kevin.plugin.v1.InfoResponse
	(*StepType)(nil),           // 3: kevin.plugin.v1.StepType
	(*ToolDefinition)(nil),     // 4: kevin.plugin.v1.ToolDefinition
	(*ConfigureRequest)(nil),   // 5: kevin.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),  // 6: kevin.plugin.v1.ConfigureResponse
	(*Environment)(nil),        // 7: kevin.plugin.v1.Environment
	(*DockerEngineConfig)(nil), // 8: kevin.plugin.v1.DockerEngineConfig
	(*Value)(nil),              // 9: kevin.plugin.v1.Value
	(*Outputs)(nil),            // 10: kevin.plugin.v1.Outputs
	(*UpRequest)(nil),          // 11: kevin.plugin.v1.UpRequest
	(*DownRequest)(nil),        // 12: kevin.plugin.v1.DownRequest
	(*Event)(nil),              // 13: kevin.plugin.v1.Event
	(*LogLine)(nil),            // 14: kevin.plugin.v1.LogLine
	(*Progress)(nil),           // 15: kevin.plugin.v1.Progress
	(*Result)(nil),             // 16: kevin.plugin.v1.Result
	(*ExposedPort)(nil),        // 17: kevin.plugin.v1.ExposedPort
	(*Detail)(nil),             // 18: kevin.plugin.v1.Detail
	(*ExportRequest)(nil),      // 19: kevin.plugin.v1.ExportRequest
	(*ExportResponse)(nil),     // 20: kevin.plugin.v1.ExportResponse
	(*ToolCallRequest)(nil),    // 21: kevin.plugin.v1.ToolCallRequest
	(*ToolCallResponse)(nil),   // 22: kevin.plugin.v1.ToolCallResponse
	(*Route)(nil),              // 23: kevin.plugin.v1.Route
	(*UserMessage)(nil),        // 24: kevin.plugin.v1.UserMessage
	nil,                        // 25: kevin.plugin.v1.Environment.ProxyEnvEntry
	nil,                        // 26: kevin.plugin.v1.Outputs.ValuesEntry
	nil,                        // 27: kevin.plugin.v1.UpRequest.DepsEntry
	nil,                        // 28: kevin.plugin.v1.DownRequest.DepsEntry
	nil,                        // 29: kevin.plugin.v1.ToolCallRequest.DepsEntry
}
var file_pb_plugin_proto_depIdxs = []int32{
	3,  // 0: kevin.plugin.v1.InfoResponse.steps:type_name -> kevin.plugin.v1.StepType
	0,  // 1: kevin.plugin.v1.StepType.kind:type_name -> kevin.plugin.v1.StepKind
	4,  // 2: kevin.plugin.v1.StepType.tools:type_name -> kevin.plugin.v1.ToolDefinition
	7,  // 3: kevin.plugin.v1.ConfigureRequest.env:type_name -> kevin.plugin.v1.Environment
	25, // 4: kevin.plugin.v1.Environment.proxy_env:type_name -> kevin.plugin.v1.Environment.ProxyEnvEntry
	26, // 5: kevin.plugin.v1.Outputs.values:type_name -> kevin.plugin.v1.Outputs.ValuesEntry
	7,  // 6: kevin.plugin.v1.UpRequest.env:type_name -> kevin.plugin.v1.Environment
	27, // 7: kevin.plugin.v1.UpRequest.deps:type_name -> kevin.plugin.v1.UpRequest.DepsEntry
	7,  // 8: kevin.plugin.v1.DownRequest.env:type_name -> kevin.plugin.v1.Environment
	28, // 9: kevin.plugin.v1.DownRequest.deps:type_name -> kevin.plugin.v1.DownRequest.DepsEntry
	10, // 10: kevin.plugin.v1.DownRequest.outputs:type_name -> kevin.plugin.v1.Outputs
	14, // 11: kevin.plugin.v1.Event.log:type_name -> kevin.plugin.v1.LogLine
	15, // 12: kevin.plugin.v1.Event.progress:type_name -> kevin.plugin.v1.Progress
	16, // 13: kevin.plugin.v1.Event.result:type_name -> kevin.plugin.v1.Result
	10, // 14: kevin.plugin.v1.Result.outputs:type_name -> kevin.plugin.v1.Outputs
	23, // 15: kevin.plugin.v1.Result.routes:type_name -> kevin.plugin.v1.Route
	17, // 16: kevin.plugin.v1.Result.exposed_ports:type_name -> kevin.plugin.v1.ExposedPort
	18, // 17: kevin.plugin.v1.Result.details:type_name -> kevin.plugin.v1.Detail
	9,  // 18: kevin.plugin.v1.Detail.value:type_name -> kevin.plugin.v1.Value
	7,  // 19: kevin.plugin.v1.ExportRequest.env:type_name -> kevin.plugin.v1.Environment
	10, // 20: kevin.plugin.v1.ExportResponse.out:type_name -> kevin.plugin.v1.Outputs
	7,  // 21: kevin.plugin.v1.ToolCallRequest.env:type_name -> kevin.plugin.v1.Environment
	29, // 22: kevin.plugin.v1.ToolCallRequest.deps:type_name -> kevin.plugin.v1.ToolCallRequest.DepsEntry
	9,  // 23: kevin.plugin.v1.Outputs.ValuesEntry.value:type_name -> kevin.plugin.v1.Value
	10, // 24: kevin.plugin.v1.UpRequest.DepsEntry.value:type_name -> kevin.plugin.v1.Outputs
	10, // 25: kevin.plugin.v1.DownRequest.DepsEntry.value:type_name -> kevin.plugin.v1.Outputs
	10, // 26: kevin.plugin.v1.ToolCallRequest.DepsEntry.value:type_name -> kevin.plugin.v1.Outputs
	1,  // 27: kevin.plugin.v1.Plugin.Info:input_type -> kevin.plugin.v1.InfoRequest
	5,  // 28: kevin.plugin.v1.Plugin.Configure:input_type -> kevin.plugin.v1.ConfigureRequest
	11, // 29: kevin.plugin.v1.Plugin.Up:input_type -> kevin.plugin.v1.UpRequest
	12, // 30: kevin.plugin.v1.Plugin.Down:input_type -> kevin.plugin.v1.DownRequest
	19, // 31: kevin.plugin.v1.Plugin.Export:input_type -> kevin.plugin.v1.ExportRequest
	21, // 32: kevin.plugin.v1.Plugin.CallTool:input_type -> kevin.plugin.v1.ToolCallRequest
	2,  // 33: kevin.plugin.v1.Plugin.Info:output_type -> kevin.plugin.v1.InfoResponse
	6,  // 34: kevin.plugin.v1.Plugin.Configure:output_type -> kevin.plugin.v1.ConfigureResponse
	13, // 35: kevin.plugin.v1.Plugin.Up:output_type -> kevin.plugin.v1.Event
	13, // 36: kevin.plugin.v1.Plugin.Down:output_type -> kevin.plugin.v1.Event
	20, // 37: kevin.plugin.v1.Plugin.Export:output_type -> kevin.plugin.v1.ExportResponse
	22, // 38: kevin.plugin.v1.Plugin.CallTool:output_type -> kevin.plugin.v1.ToolCallResponse
	33, // [33:39] is the sub-list for method output_type
	27, // [27:33] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_pb_plugin_proto_init() }
func file_pb_plugin_proto_init() {
	if File_pb_plugin_proto != nil {
		return
	}
	file_pb_plugin_proto_msgTypes[8].OneofWrappers = []any{
		(*Value_StringValue)(nil),
	}
	file_pb_plugin_proto_msgTypes[12].OneofWrappers = []any{
		(*Event_Log)(nil),
		(*Event_Progress)(nil),
		(*Event_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_plugin_proto_rawDesc), len(file_pb_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_plugin_proto_goTypes,
		DependencyIndexes: file_pb_plugin_proto_depIdxs,
		EnumInfos:         file_pb_plugin_proto_enumTypes,
		MessageInfos:      file_pb_plugin_proto_msgTypes,
	}.Build()
	File_pb_plugin_proto = out.File
	file_pb_plugin_proto_goTypes = nil
	file_pb_plugin_proto_depIdxs = nil
}
