// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pb/relay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterCaptureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID names the step (and, for a multi-node step, the node) this
	// namespace belongs to, for logging.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// NetnsPath is the host path of the network namespace, such as
	// "/var/run/docker/netns/1234abcd".
	NetnsPath string `protobuf:"bytes,2,opt,name=netns_path,json=netnsPath,proto3" json:"netns_path,omitempty"`
	// ExcludeCIDRs lists destination CIDRs that must never be redirected to
	// the relay. See the RegisterCapture RPC comment for what its presence
	// means.
	ExcludeCidrs  []string `protobuf:"bytes,3,rep,name=exclude_cidrs,json=excludeCidrs,proto3" json:"exclude_cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCaptureRequest) Reset() {
	*x = RegisterCaptureRequest{}
	mi := &file_pb_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCaptureRequest) ProtoMessage() {}

func (x *RegisterCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCaptureRequest.ProtoReflect.Descriptor instead.
func (*RegisterCaptureRequest) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCaptureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterCaptureRequest) GetNetnsPath() string {
	if x != nil {
		return x.NetnsPath
	}
	return ""
}

func (x *RegisterCaptureRequest) GetExcludeCidrs() []string {
	if x != nil {
		return x.ExcludeCidrs
	}
	return nil
}

type RegisterCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCaptureResponse) Reset() {
	*x = RegisterCaptureResponse{}
	mi := &file_pb_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCaptureResponse) ProtoMessage() {}

func (x *RegisterCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCaptureResponse.ProtoReflect.Descriptor instead.
func (*RegisterCaptureResponse) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{1}
}

type EnsureListenerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host is the real-world hostname an intercept route names. Empty for a
	// step whose egress the relay already captures directly, which needs no
	// DNS answer of its own.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Ports lists the ports a route's Intercept entry names, beyond the
	// relay's always-open 80 and 443.
	Ports         []int32 `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureListenerRequest) Reset() {
	*x = EnsureListenerRequest{}
	mi := &file_pb_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureListenerRequest) ProtoMessage() {}

func (x *EnsureListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureListenerRequest.ProtoReflect.Descriptor instead.
func (*EnsureListenerRequest) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{2}
}

func (x *EnsureListenerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EnsureListenerRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type EnsureListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureListenerResponse) Reset() {
	*x = EnsureListenerResponse{}
	mi := &file_pb_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureListenerResponse) ProtoMessage() {}

func (x *EnsureListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureListenerResponse.ProtoReflect.Descriptor instead.
func (*EnsureListenerResponse) Descriptor() ([]byte, []int) {
	return file_pb_relay_proto_rawDescGZIP(), []int{3}
}

var File_pb_relay_proto protoreflect.FileDescriptor

const file_pb_relay_proto_rawDesc = "" +
	"\n" +
	"\x0epb/relay.proto\x12\x0ekevin.relay.v1\"l\n" +
	"\x16RegisterCaptureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"netns_path\x18\x02 \x01(\tR\tnetnsPath\x12#\n" +
	"\rexclude_cidrs\x18\x03 \x03(\tR\fexcludeCidrs\"\x19\n" +
	"\x17RegisterCaptureResponse\"A\n" +
	"\x15EnsureListenerRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\x05R\x05ports\"\x18\n" +
	"\x16EnsureListenerResponse2\xd3\x01\n" +
	"\fRelayControl\x12b\n" +
	"\x0fRegisterCapture\x12&.kevin.relay.v1.RegisterCaptureRequest\x1a'.kevin.relay.v1.RegisterCaptureResponse\x12_\n" +
	"\x0eEnsureListener\x12%.kevin.relay.v1.EnsureListenerRequest\x1a&.kevin.relay.v1.EnsureListenerResponseB,Z*github.com/justenwalker/kevin/protos/pb;pbb\x06proto3"

var (
	file_pb_relay_proto_rawDescOnce sync.Once
	file_pb_relay_proto_rawDescData []byte
)

func file_pb_relay_proto_rawDescGZIP() []byte {
	file_pb_relay_proto_rawDescOnce.Do(func() {
		file_pb_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_relay_proto_rawDesc), len(file_pb_relay_proto_rawDesc)))
	})
	return file_pb_relay_proto_rawDescData
}

var file_pb_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_relay_proto_goTypes = []any{
	(*RegisterCaptureRequest)(nil),  // 0: kevin.relay.v1.RegisterCaptureRequest
	(*RegisterCaptureResponse)(nil), // 1: kevin.relay.v1.RegisterCaptureResponse
	(*EnsureListenerRequest)(nil),   // 2: kevin.relay.v1.EnsureListenerRequest
	(*EnsureListenerResponse)(nil),  // 3: kevin.relay.v1.EnsureListenerResponse
}
var file_pb_relay_proto_depIdxs = []int32{
	0, // 0: kevin.relay.v1.RelayControl.RegisterCapture:input_type -> kevin.relay.v1.RegisterCaptureRequest
	2, // 1: kevin.relay.v1.RelayControl.EnsureListener:input_type -> kevin.relay.v1.EnsureListenerRequest
	1, // 2: kevin.relay.v1.RelayControl.RegisterCapture:output_type -> kevin.relay.v1.RegisterCaptureResponse
	3, // 3: kevin.relay.v1.RelayControl.EnsureListener:output_type -> kevin.relay.v1.EnsureListenerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_relay_proto_init() }
func file_pb_relay_proto_init() {
	if File_pb_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_relay_proto_rawDesc), len(file_pb_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_relay_proto_goTypes,
		DependencyIndexes: file_pb_relay_proto_depIdxs,
		MessageInfos:      file_pb_relay_proto_msgTypes,
	}.Build()
	File_pb_relay_proto = out.File
	file_pb_relay_proto_goTypes = nil
	file_pb_relay_proto_depIdxs = nil
}
