// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pb/relay.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayControl_RegisterCapture_FullMethodName = "/kevin.relay.v1.RelayControl/RegisterCapture"
	RelayControl_EnsureListener_FullMethodName  = "/kevin.relay.v1.RelayControl/EnsureListener"
)

// RelayControlClient is the client API for RelayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RelayControl is the control channel between kevin's engine and one
// project's relay container. It is served over mutual TLS: only a caller
// holding a client certificate signed by the project's own intermediate
// authority can call it.
type RelayControlClient interface {
	// RegisterCapture tells the relay to redirect traffic through the
	// namespace at netns_path to itself, so egress is captured transparently
	// - regardless of whether a workload resolves the relay's own DNS or
	// honors a proxy environment variable. With no exclude_cidrs, netns_path
	// is a single workload's own namespace, captured at its own outbound
	// connections (a builtin:container step). With exclude_cidrs set,
	// netns_path routes traffic for others - a builtin:kind node - and is
	// captured at what transits it instead, skipping any destination in
	// exclude_cidrs so pod-to-pod and pod-to-service traffic isn't touched.
	RegisterCapture(ctx context.Context, in *RegisterCaptureRequest, opts ...grpc.CallOption) (*RegisterCaptureResponse, error)
	// EnsureListener registers an External route: it answers the relay's own
	// DNS for host - exactly, or by "*." wildcard, the same rule builtin:route
	// itself applies - since a workload with no network namespace the relay
	// can capture (a kind pod) has no other way to reach the interception; it
	// also opens a listener for each of ports beyond the relay's always-on 80
	// and 443, and re-applies capture on every container RegisterCapture has
	// already registered - so a route declared after some containers already
	// exist still reaches them.
	EnsureListener(ctx context.Context, in *EnsureListenerRequest, opts ...grpc.CallOption) (*EnsureListenerResponse, error)
}

type relayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayControlClient(cc grpc.ClientConnInterface) RelayControlClient {
	return &relayControlClient{cc}
}

func (c *relayControlClient) RegisterCapture(ctx context.Context, in *RegisterCaptureRequest, opts ...grpc.CallOption) (*RegisterCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCaptureResponse)
	err := c.cc.Invoke(ctx, RelayControl_RegisterCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) EnsureListener(ctx context.Context, in *EnsureListenerRequest, opts ...grpc.CallOption) (*EnsureListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureListenerResponse)
	err := c.cc.Invoke(ctx, RelayControl_EnsureListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayControlServer is the server API for RelayControl service.
// All implementations should embed UnimplementedRelayControlServer
// for forward compatibility.
//
// RelayControl is the control channel between kevin's engine and one
// project's relay container. It is served over mutual TLS: only a caller
// holding a client certificate signed by the project's own intermediate
// authority can call it.
type RelayControlServer interface {
	// RegisterCapture tells the relay to redirect traffic through the
	// namespace at netns_path to itself, so egress is captured transparently
	// - regardless of whether a workload resolves the relay's own DNS or
	// honors a proxy environment variable. With no exclude_cidrs, netns_path
	// is a single workload's own namespace, captured at its own outbound
	// connections (a builtin:container step). With exclude_cidrs set,
	// netns_path routes traffic for others - a builtin:kind node - and is
	// captured at what transits it instead, skipping any destination in
	// exclude_cidrs so pod-to-pod and pod-to-service traffic isn't touched.
	RegisterCapture(context.Context, *RegisterCaptureRequest) (*RegisterCaptureResponse, error)
	// EnsureListener registers an External route: it answers the relay's own
	// DNS for host - exactly, or by "*." wildcard, the same rule builtin:route
	// itself applies - since a workload with no network namespace the relay
	// can capture (a kind pod) has no other way to reach the interception; it
	// also opens a listener for each of ports beyond the relay's always-on 80
	// and 443, and re-applies capture on every container RegisterCapture has
	// already registered - so a route declared after some containers already
	// exist still reaches them.
	EnsureListener(context.Context, *EnsureListenerRequest) (*EnsureListenerResponse, error)
}

// UnimplementedRelayControlServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayControlServer struct{}

func (UnimplementedRelayControlServer) RegisterCapture(context.Context, *RegisterCaptureRequest) (*RegisterCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCapture not implemented")
}
func (UnimplementedRelayControlServer) EnsureListener(context.Context, *EnsureListenerRequest) (*EnsureListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureListener not implemented")
}
func (UnimplementedRelayControlServer) testEmbeddedByValue() {}

// UnsafeRelayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayControlServer will
// result in compilation errors.
type UnsafeRelayControlServer interface {
	mustEmbedUnimplementedRelayControlServer()
}

func RegisterRelayControlServer(s grpc.ServiceRegistrar, srv RelayControlServer) {
	// If the following call panics, it indicates UnimplementedRelayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayControl_ServiceDesc, srv)
}

func _RelayControl_RegisterCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).RegisterCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_RegisterCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).RegisterCapture(ctx, req.(*RegisterCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_EnsureListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).EnsureListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_EnsureListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).EnsureListener(ctx, req.(*EnsureListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayControl_ServiceDesc is the grpc.ServiceDesc for RelayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kevin.relay.v1.RelayControl",
	HandlerType: (*RelayControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCapture",
			Handler:    _RelayControl_RegisterCapture_Handler,
		},
		{
			MethodName: "EnsureListener",
			Handler:    _RelayControl_EnsureListener_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/relay.proto",
}
