// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helm

import (
	"context"

	"github.com/justenwalker/kevin/internal/command/helm"
	mock "github.com/stretchr/testify/mock"
)

// newMockcli creates a new instance of mockcli. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcli(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcli {
	mock := &mockcli{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcli is an autogenerated mock type for the cli type
type mockcli struct {
	mock.Mock
}

type mockcli_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcli) EXPECT() *mockcli_Expecter {
	return &mockcli_Expecter{mock: &_m.Mock}
}

// Uninstall provides a mock function for the type mockcli
func (_mock *mockcli) Uninstall(ctx context.Context, spec helm.UninstallSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Uninstall")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helm.UninstallSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, helm.UninstallSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, helm.UninstallSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcli_Uninstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uninstall'
type mockcli_Uninstall_Call struct {
	*mock.Call
}

// Uninstall is a helper method to define mock.On call
//   - ctx context.Context
//   - spec helm.UninstallSpec
func (_e *mockcli_Expecter) Uninstall(ctx any, spec any) *mockcli_Uninstall_Call {
	return &mockcli_Uninstall_Call{Call: _e.mock.On("Uninstall", ctx, spec)}
}

func (_c *mockcli_Uninstall_Call) Run(run func(ctx context.Context, spec helm.UninstallSpec)) *mockcli_Uninstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helm.UninstallSpec
		if args[1] != nil {
			arg1 = args[1].(helm.UninstallSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcli_Uninstall_Call) Return(s string, err error) *mockcli_Uninstall_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockcli_Uninstall_Call) RunAndReturn(run func(ctx context.Context, spec helm.UninstallSpec) (string, error)) *mockcli_Uninstall_Call {
	_c.Call.Return(run)
	return _c
}

// UpgradeInstall provides a mock function for the type mockcli
func (_mock *mockcli) UpgradeInstall(ctx context.Context, spec helm.UpgradeSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for UpgradeInstall")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helm.UpgradeSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, helm.UpgradeSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, helm.UpgradeSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcli_UpgradeInstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpgradeInstall'
type mockcli_UpgradeInstall_Call struct {
	*mock.Call
}

// UpgradeInstall is a helper method to define mock.On call
//   - ctx context.Context
//   - spec helm.UpgradeSpec
func (_e *mockcli_Expecter) UpgradeInstall(ctx any, spec any) *mockcli_UpgradeInstall_Call {
	return &mockcli_UpgradeInstall_Call{Call: _e.mock.On("UpgradeInstall", ctx, spec)}
}

func (_c *mockcli_UpgradeInstall_Call) Run(run func(ctx context.Context, spec helm.UpgradeSpec)) *mockcli_UpgradeInstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helm.UpgradeSpec
		if args[1] != nil {
			arg1 = args[1].(helm.UpgradeSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcli_UpgradeInstall_Call) Return(s string, err error) *mockcli_UpgradeInstall_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockcli_UpgradeInstall_Call) RunAndReturn(run func(ctx context.Context, spec helm.UpgradeSpec) (string, error)) *mockcli_UpgradeInstall_Call {
	_c.Call.Return(run)
	return _c
}
