// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package commandtest

import (
	"context"
	"os/exec"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockRunner
func (_mock *MockRunner) Run(ctx context.Context, cmd *exec.Cmd) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *exec.Cmd) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *exec.Cmd
func (_e *MockRunner_Expecter) Run(ctx any, cmd any) *MockRunner_Run_Call {
	return &MockRunner_Run_Call{Call: _e.mock.On("Run", ctx, cmd)}
}

func (_c *MockRunner_Run_Call) Run(run func(ctx context.Context, cmd *exec.Cmd)) *MockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *exec.Cmd
		if args[1] != nil {
			arg1 = args[1].(*exec.Cmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRunner_Run_Call) Return(err error) *MockRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Run_Call) RunAndReturn(run func(ctx context.Context, cmd *exec.Cmd) error) *MockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStarter creates a new instance of MockStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStarter {
	mock := &MockStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStarter is an autogenerated mock type for the Starter type
type MockStarter struct {
	mock.Mock
}

type MockStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStarter) EXPECT() *MockStarter_Expecter {
	return &MockStarter_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockStarter
func (_mock *MockStarter) Start(ctx context.Context, cmd *exec.Cmd) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *exec.Cmd) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStarter_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockStarter_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *exec.Cmd
func (_e *MockStarter_Expecter) Start(ctx any, cmd any) *MockStarter_Start_Call {
	return &MockStarter_Start_Call{Call: _e.mock.On("Start", ctx, cmd)}
}

func (_c *MockStarter_Start_Call) Run(run func(ctx context.Context, cmd *exec.Cmd)) *MockStarter_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *exec.Cmd
		if args[1] != nil {
			arg1 = args[1].(*exec.Cmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStarter_Start_Call) Return(err error) *MockStarter_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStarter_Start_Call) RunAndReturn(run func(ctx context.Context, cmd *exec.Cmd) error) *MockStarter_Start_Call {
	_c.Call.Return(run)
	return _c
}
