// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kubernetes

import (
	"context"
	"io"

	"github.com/justenwalker/kevin/internal/command/kind"
	mock "github.com/stretchr/testify/mock"
)

// newMockkindCLI creates a new instance of mockkindCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockkindCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockkindCLI {
	mock := &mockkindCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockkindCLI is an autogenerated mock type for the kindCLI type
type mockkindCLI struct {
	mock.Mock
}

type mockkindCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *mockkindCLI) EXPECT() *mockkindCLI_Expecter {
	return &mockkindCLI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockkindCLI
func (_mock *mockkindCLI) Create(ctx context.Context, spec kind.CreateSpec, stdout io.Writer, stderr io.Writer) error {
	ret := _mock.Called(ctx, spec, stdout, stderr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kind.CreateSpec, io.Writer, io.Writer) error); ok {
		r0 = returnFunc(ctx, spec, stdout, stderr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkindCLI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockkindCLI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spec kind.CreateSpec
//   - stdout io.Writer
//   - stderr io.Writer
func (_e *mockkindCLI_Expecter) Create(ctx any, spec any, stdout any, stderr any) *mockkindCLI_Create_Call {
	return &mockkindCLI_Create_Call{Call: _e.mock.On("Create", ctx, spec, stdout, stderr)}
}

func (_c *mockkindCLI_Create_Call) Run(run func(ctx context.Context, spec kind.CreateSpec, stdout io.Writer, stderr io.Writer)) *mockkindCLI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kind.CreateSpec
		if args[1] != nil {
			arg1 = args[1].(kind.CreateSpec)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockkindCLI_Create_Call) Return(err error) *mockkindCLI_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkindCLI_Create_Call) RunAndReturn(run func(ctx context.Context, spec kind.CreateSpec, stdout io.Writer, stderr io.Writer) error) *mockkindCLI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockkindCLI
func (_mock *mockkindCLI) Delete(ctx context.Context, spec kind.DeleteSpec, stderr io.Writer) error {
	ret := _mock.Called(ctx, spec, stderr)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kind.DeleteSpec, io.Writer) error); ok {
		r0 = returnFunc(ctx, spec, stderr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkindCLI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockkindCLI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - spec kind.DeleteSpec
//   - stderr io.Writer
func (_e *mockkindCLI_Expecter) Delete(ctx any, spec any, stderr any) *mockkindCLI_Delete_Call {
	return &mockkindCLI_Delete_Call{Call: _e.mock.On("Delete", ctx, spec, stderr)}
}

func (_c *mockkindCLI_Delete_Call) Run(run func(ctx context.Context, spec kind.DeleteSpec, stderr io.Writer)) *mockkindCLI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kind.DeleteSpec
		if args[1] != nil {
			arg1 = args[1].(kind.DeleteSpec)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockkindCLI_Delete_Call) Return(err error) *mockkindCLI_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkindCLI_Delete_Call) RunAndReturn(run func(ctx context.Context, spec kind.DeleteSpec, stderr io.Writer) error) *mockkindCLI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodes provides a mock function for the type mockkindCLI
func (_mock *mockkindCLI) GetNodes(ctx context.Context, name string, env map[string]string) ([]string, error) {
	ret := _mock.Called(ctx, name, env)

	if len(ret) == 0 {
		panic("no return value specified for GetNodes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) ([]string, error)); ok {
		return returnFunc(ctx, name, env)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) []string); ok {
		r0 = returnFunc(ctx, name, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, name, env)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkindCLI_GetNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodes'
type mockkindCLI_GetNodes_Call struct {
	*mock.Call
}

// GetNodes is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - env map[string]string
func (_e *mockkindCLI_Expecter) GetNodes(ctx any, name any, env any) *mockkindCLI_GetNodes_Call {
	return &mockkindCLI_GetNodes_Call{Call: _e.mock.On("GetNodes", ctx, name, env)}
}

func (_c *mockkindCLI_GetNodes_Call) Run(run func(ctx context.Context, name string, env map[string]string)) *mockkindCLI_GetNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockkindCLI_GetNodes_Call) Return(strings []string, err error) *mockkindCLI_GetNodes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockkindCLI_GetNodes_Call) RunAndReturn(run func(ctx context.Context, name string, env map[string]string) ([]string, error)) *mockkindCLI_GetNodes_Call {
	_c.Call.Return(run)
	return _c
}

// LoadImageArchive provides a mock function for the type mockkindCLI
func (_mock *mockkindCLI) LoadImageArchive(ctx context.Context, spec kind.LoadImageArchiveSpec, stderr io.Writer) error {
	ret := _mock.Called(ctx, spec, stderr)

	if len(ret) == 0 {
		panic("no return value specified for LoadImageArchive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kind.LoadImageArchiveSpec, io.Writer) error); ok {
		r0 = returnFunc(ctx, spec, stderr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkindCLI_LoadImageArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadImageArchive'
type mockkindCLI_LoadImageArchive_Call struct {
	*mock.Call
}

// LoadImageArchive is a helper method to define mock.On call
//   - ctx context.Context
//   - spec kind.LoadImageArchiveSpec
//   - stderr io.Writer
func (_e *mockkindCLI_Expecter) LoadImageArchive(ctx any, spec any, stderr any) *mockkindCLI_LoadImageArchive_Call {
	return &mockkindCLI_LoadImageArchive_Call{Call: _e.mock.On("LoadImageArchive", ctx, spec, stderr)}
}

func (_c *mockkindCLI_LoadImageArchive_Call) Run(run func(ctx context.Context, spec kind.LoadImageArchiveSpec, stderr io.Writer)) *mockkindCLI_LoadImageArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kind.LoadImageArchiveSpec
		if args[1] != nil {
			arg1 = args[1].(kind.LoadImageArchiveSpec)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockkindCLI_LoadImageArchive_Call) Return(err error) *mockkindCLI_LoadImageArchive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkindCLI_LoadImageArchive_Call) RunAndReturn(run func(ctx context.Context, spec kind.LoadImageArchiveSpec, stderr io.Writer) error) *mockkindCLI_LoadImageArchive_Call {
	_c.Call.Return(run)
	return _c
}
